module:
  address: 0
  addtoany: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  advagg: 0
  autologout: 0
  automated_cron: 0
  ban: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  config: 0
  config_update: 0
  consumers: 0
  contact: 0
  contact_storage: 0
  content_moderation: 0
  contextual: 0
  crop: 0
  ctools: 0
  ctools_block: 0
  datetime: 0
  dblog: 0
  diff: 0
  dropzonejs: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  embed: 0
  entity_block: 0
  entity_browser: 0
  entity_embed: 0
  entity_reference: 0
  entity_reference_revisions: 0
  features: 0
  features_ui: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  geofield: 0
  geofield_map: 0
  geophp: 0
  help: 0
  history: 0
  image: 0
  image_widget_crop: 0
  inline_entity_form: 0
  inline_form_errors: 0
  jsonapi: 0
  layout_discovery: 0
  leaflet: 0
  leaflet_markercluster: 0
  leaflet_more_maps: 0
  leaflet_views: 0
  libraries: 0
  lightning_api: 0
  lightning_contact_form: 0
  lightning_core: 0
  lightning_landing_page: 0
  lightning_layout: 0
  lightning_media: 0
  lightning_media_bulk_upload: 0
  lightning_media_document: 0
  lightning_media_image: 0
  lightning_media_instagram: 0
  lightning_media_twitter: 0
  lightning_media_video: 0
  lightning_page: 0
  lightning_roles: 0
  lightning_scheduler: 0
  lightning_search: 0
  lightning_workflow: 0
  link: 0
  login_security: 0
  media: 0
  media_entity_instagram: 0
  media_entity_twitter: 0
  menu_ui: 0
  metatag: 0
  migrate: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_tools: 0
  node: 0
  openapi: 0
  openapi_redoc: 0
  options: 0
  page_cache: 0
  panelizer: 0
  panelizer_quickedit: 0
  panels: 0
  panels_ipe: 0
  path: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  schemata: 0
  schemata_json_schema: 0
  search_api: 0
  search_api_db: 0
  serialization: 0
  settings_tray: 0
  shortcut: 0
  simple_oauth: 0
  simple_oauth_extras: 0
  smtp: 0
  styled_google_map: 0
  superfish: 0
  system: 0
  taxonomy: 0
  taxonomy_manager: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  ultimate_cron: 0
  update: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  views_infinite_scroll: 0
  views_ui: 0
  webform: 0
  webform_image_select: 0
  webform_node: 0
  webform_scheduled_email: 0
  webform_templates: 0
  webform_ui: 0
  workflows: 0
  menu_link_content: 1
  pathauto: 1
  webform_bootstrap: 1
  views: 10
  paragraphs: 11
  lightning: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  adminimal_theme: 0
  openelections: 0
profile: lightning
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
